server:
  port: 8080

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10

spring:
  datasource:
    url: jdbc:h2:file:./users;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false

  main:
    allow-circular-references: true

